name: Process sheets

on:
  workflow_dispatch:
  # schedule:
    # - cron: '0 3 */3 * *'

jobs:
  download-and-uplift:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install git+https://github.com/opengeospatial/ogc-na-tools.git
          pip3 install pandas openpyxl
      - name: Process files
        run: |
          cd sources
          python excel2csv.py

      - name: Process files
        env:
          DB_USERNAME: admin
          DB_PASSWORD: ${{ secrets.UPLOAD_GRAPH_STORE_PASSWORD }}
        run: |
          find . -wholename '**/sources/*.csv' | while read CSV_FILE; do python -m ogc.na.ingest_json \
            --skip-on-missing-context --json-ld --context csv2python.yml "${CSV_FILE}" > "${CSV_FILE}.json"
          done

          python -m ogc.na.ingest_json --batch --skip-on-missing-context --all \
            --json-ld --ttl --work-dir . --domain-config .ogc/catalog.ttl
          # python -m ogc.na.update_vocabs -w . .ogc/catalog.ttl --use-git-status \
          #  --base-uri https://raw.githubusercontent.com/${{github.repository}}/${{github.ref_name}} \
          #  --update --graph-store http://defs-dev.opengis.net:8061/fuseki-hosted/data
      - name: Add and commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Files download and semantic uplift"
          default_author: github_actions
